import { Inter } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/GlobalRedux/GlobalProvider";
import RQProvider from "@/utils/RQProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chatterbot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <GlobalProvider>
        <body className={inter.className}>
          <RQProvider>{children}</RQProvider>
        </body>
      </GlobalProvider>
    </html>
  );
}
